updates:
  - file: "stable/cluster-kube-descheduler-operator.v{MAJOR}.{MINOR}.0.clusterserviceversion.yaml" # relative to this file
    update_list:
    # replace metadata.name value
    - search: "clusterkubedescheduleroperator.v{MAJOR}.{MINOR}.0"
      replace: "clusterkubedescheduleroperator.{FULL_VER}"
    # replace entire version line, otherwise would replace {MAJOR}.{MINOR}.0 anywhere
    - search: "version: {MAJOR}.{MINOR}.0"
      replace: "version: {FULL_VER}"
    - search: 'olm.skipRange: ">=4.11.0 <{MAJOR}.{MINOR}.0"'
      replace: 'olm.skipRange: ">=4.11.0 <{FULL_VER}"'
  - file: "cluster-kube-descheduler-operator.package.yaml"
    update_list:
    - search: "currentCSV: cluster-kube-descheduler-operator.v{MAJOR}.{MINOR}.0"
      replace: "currentCSV: cluster-kube-descheduler-operator.{FULL_VER}"
