apiVersion: apps/v1
kind: Deployment
metadata:
  name: "descheduler"
  namespace: "openshift-kube-descheduler-operator"
  labels:
    app: "descheduler"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "descheduler"
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: openshift-descheduler
      labels:
        app: "descheduler"
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: "policy-volume"
          configMap:
            name: "descheduler"
        - name: certs-dir
          secret:
            secretName: kube-descheduler-serving-cert
      priorityClassName: "system-cluster-critical"
      restartPolicy: "Always"
      containers:
        - name: "openshift-descheduler"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          image: ${IMAGE}
          resources:
            requests:
              cpu: "100m"
              memory: "500Mi"
          command: ["/bin/descheduler"]
          args:
            - --policy-config-file=/policy-dir/policy.yaml
            - --logging-format=text
            - --tls-cert-file=/certs-dir/tls.crt
            - --tls-private-key-file=/certs-dir/tls.key
          volumeMounts:
            - mountPath: "/policy-dir"
              name: "policy-volume"
            - mountPath: "/certs-dir"
              name: certs-dir
      serviceAccountName: "openshift-descheduler-operand"
